# Generated by Django 5.1.2 on 2024-11-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество (Прозвище)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('biography', models.TextField(blank=True, verbose_name='Биография')),
                ('date_of_birth', models.DateTimeField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('passport_photo', models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото на паспорт')),
                ('is_adult', models.BooleanField(default=True, verbose_name='Совершеннолетие')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Homework.profession', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Человеки',
                'ordering': ['-created_at'],
            },
        ),
    ]
